name: Label PRs

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: write

jobs:
  label_approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Label approved PRs
        uses: koj-co/label-approved-action@1.0.0
        with:
          labels: approved
          approvals: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
